- name: Print calculated path
  debug:
    msg: "My calculated chdir path: {{ playbook_dir | dirname }}"
- name: Create namespace for SPE
  command: kubectl apply -f namespace-spe.yml --kubeconfig=/home/akshar/.kube/config
  args:
    chdir: "{{ playbook_dir | dirname }}"
  register: namespace_output
  become: yes

- name: Claim Persistent Volume for MySQL
  command: kubectl apply -f pv-pvc.yml --kubeconfig=/home/akshar/.kube/config
  args:
    chdir: "{{ playbook_dir | dirname }}"
  register: pv_pvc_output
  become: yes

- name: Apply MySQL deployment
  command: kubectl apply -f mysql-deployment.yml --kubeconfig=/home/akshar/.kube/config
  args:
    chdir: "{{ playbook_dir | dirname }}"
  register: mysql_output
  become: yes

- name: Show MySQL apply output
  debug:
    var: mysql_output.stdout_lines

- name: Wait for MySQL to stabilize
  pause:
    seconds: 90

- name: Apply Config Map for frontend and for microservices
  command: kubectl apply -f spe-configmap.yml --kubeconfig=/home/akshar/.kube/config
  args:
     chdir: "{{ playbook_dir | dirname }}"
  register: config_map_output
  become: yes

- name: Apply all microservices
  shell: |
    kubectl apply -f auth-microservice-deployment.yml --kubeconfig=/home/akshar/.kube/config
    kubectl apply -f user-service-deployment.yml --kubeconfig=/home/akshar/.kube/config
    kubectl apply -f appointment-service-deployment.yml --kubeconfig=/home/akshar/.kube/config
    kubectl apply -f gateway-service-deployment.yml --kubeconfig=/home/akshar/.kube/config
    kubectl apply -f frontend-nginx-deployment.yml --kubeconfig=/home/akshar/.kube/config
    kubectl apply -f websocket-deployment.yml --kubeconfig=/home/akshar/.kube/config
  args:
    chdir: "{{ playbook_dir | dirname }}"
  register: services_output
  become: yes

- name: Show services deployment output
  debug:
    var: services_output.stdout_lines

- name: Apply ingress deployment
  command: kubectl apply -f ingress-deployment.yml --kubeconfig=/home/akshar/.kube/config
  args:
     chdir: "{{ playbook_dir | dirname }}"
  register: ingress_output
  become: yes

- name: Show ingress deployment output
  debug:
    var: ingress_output.stdout_lines
