- name: Print calculated path
  debug:
    msg: "My calculated chdir path: {{ playbook_dir | dirname }}"
    
- name: Apply MySQL deployment
  command: kubectl apply -f mysql-deployment.yml --kubeconfig=/home/akshar/.kube/config
  args:
     chdir: "{{ playbook_dir | dirname }}"
  register: mysql_output
  become: yes

- name: Show MySQL apply output
  debug:
    var: mysql_output.stdout_lines

- name: Wait for ELK and MySQL to stabilize
  pause:
    seconds: 60

- name: Apply all microservices
  shell: |
    kubectl apply -f auth-microservice-deployment.yml --kubeconfig=/home/akshar/.kube/config
    kubectl apply -f user-service-deployment.yml --kubeconfig=/home/akshar/.kube/config
    kubectl apply -f appointment-service-deployment.yml --kubeconfig=/home/akshar/.kube/config
    kubectl apply -f gateway-service-deployment.yml --kubeconfig=/home/akshar/.kube/config
  args:
    chdir: "{{ playbook_dir | dirname }}"
  register: services_output
  become: yes

- name: Show services deployment output
  debug:
    var: services_output.stdout_lines

- name: Apply ingress deployment
  command: kubectl apply -f ingress-deployment.yml --kubeconfig=/home/akshar/.kube/config
  args:
     chdir: "{{ playbook_dir | dirname }}"
  register: ingress_output
  become: yes

- name: Show ingress deployment output
  debug:
    var: ingress_output.stdout_lines
