apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-microservice
  namespace: spe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-microservice
  template:
    metadata:
      labels:
        app: auth-microservice
    spec:
      containers:
        - name: auth
          image: akdev6298/authenticationandauthorizationmicroservice:0.0.5
          ports:
            - containerPort: 3001
          env:
            - name: SPRING_APPLICATION_NAME
              value: auth-microservice
            - name: SERVER_PORT
              value: "3001"
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql.spe.svc.cluster.local:3306/SPE?useSSL=false&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true
            - name: SPRING_DATASOURCE_USERNAME
              value: root
            - name: SPRING_DATASOURCE_PASSWORD
              value: root
            - name: SPRING_DATASOURCE_DRIVER_CLASS_NAME
              value: com.mysql.cj.jdbc.Driver
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              value: update
            - name: SPRING_JPA_SHOW_SQL
              value: "true"
            - name: SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL
              value: "true"
            - name: SPRING_JPA_GENERATE_DDL
              value: "true"
            - name: SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT
              value: org.hibernate.dialect.MySQLDialect
            - name: MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE
              value: health,info
            - name: SECURITY_JWT_SECRET_KEY
              value: eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ
            - name: SECURITY_JWT_EXPIRATION_TIME
              value: "860000"
---
apiVersion: v1
kind: Service
metadata:
  name: auth-microservice
  namespace: spe
spec:
  selector:
    app: auth-microservice
  ports:
    - port: 3001
      targetPort: 3001
  type: ClusterIP
