apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: spe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: frontend-app:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 80
          volumeMounts:
            - name: config-volume
              mountPath: /usr/share/nginx/html/env.js
              subPath: env.js
              readOnly: true
      volumes:
        - name: config-volume
          configMap:
            name: app-config

---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: spe
spec:
  selector:
    app: frontend
  ports:
    - port: 80
      targetPort: 80
  type: ClusterIP