apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-service
  namespace: spe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway-service
  template:
    metadata:
      labels:
        app: gateway-service
    spec:
      containers:
        - name: gateway
          image: akdev6298/gateway-service:latest
          ports:
            - containerPort: 8765
          env:
            - name: allowed.origins
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: allowed.origins
            - name: MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE
              value: health,info,prometheus
            - name: MANAGEMENT_ENDPOINT_PROMETHEUS_ENABLED
              value: "true"
            - name: MANAGEMENT_METRICS_WEB_SERVER_REQUEST_ENABLED
              value: "true"
---
apiVersion: v1
kind: Service
metadata:
  name: gateway-service
  namespace: spe
spec:
  selector:
    app: gateway-service
  ports:
    - port: 80
      targetPort: 8765
  type: ClusterIP
