# Persistent Volume (PV) for MySQL
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
  namespace: spe
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  hostPath:
    path: /mnt/data/mysql/SPE
    type: Directory
---
# Persistent Volume Claim (PVC) for MySQL
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  namespace: spe
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
