---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: spe
data:
  env.js: |
    window.env = {
        VITE_API_BASE_URL: "http://gateway.local",
        VITE_BACKEND_URL: "http://backend.local",
        APP_NAME: "Health-Check",
        VERSION: "1.0.0",
        DEBUG: false
    };
  allowed.origins:  "http://frontend.local"
